//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class alertSystemEntities : DbContext
    {
        public alertSystemEntities()
            : base("name=alertSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alert> Alerts { get; set; }
        public DbSet<Source> Sources { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ParserTypes> ParserTypes { get; set; }
        public DbSet<AlertCategory> AlertCategory { get; set; }
        public DbSet<UserAlertQueue> UserAlertQueue { get; set; }
        public DbSet<Element> Elements { get; set; }
        public DbSet<Course> Courses1 { get; set; }
    }
}
