//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public int Id { get; set; }
        public string TextContent { get; set; }
        public byte[] BinaryContent { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastChangedDate { get; set; }
        public int CursId { get; set; }
        public string Type { get; set; }
    
        public virtual Course course { get; set; }
    }
}
