//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public Source()
        {
            this.Alerts = new HashSet<Alert>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<Alert> Alerts { get; set; }
    }
}
